---
- name: Base | Setup OS variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: baseline

- include_tasks: install.yml  # Install packages
- include_tasks: config.yml   # Configuration 
- include_tasks: security.yml # Security settings
- include_tasks: users.yml    # ssh keys and users
