---
- name: Users | Add task runners group
  group:
    name: "taskrunners"
    state: present
  tags:
    - baseline
    - admin

- name: Users | Add task runner user
  user:
    name: taskrunner
    state: present
    comment: "Task Runner"
    shell: "/bin/bash"
    groups: "taskrunners"
  tags:
    - baseline
    - admin

- name: Users | Task Runners sudo
  lineinfile:
    dest: /etc/sudoers.d/taskrunners
    state: present
    create: yes
    regexp: '^%taskrunners'
    line: '%taskrunners ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - baseline
    - admin

- name: "Users | Set up keys for Task Runner"
  authorized_key:
    user: taskrunner
    key: "{{ baseline_taskrunner_key }}"
  when: baseline_taskrunner_key is defined  
  tags:
    - baseline
    - admin
    
- name: Users | Add user groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ baseline_user_groups }}"
  tags:
    - baseline
    - users

- name: Users | Add users
  user:
    name: "{{ item.name }}"
    state: present
    comment: "{{ item.comment|default('') }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    groups: "{{ ','.join(item.groups) if item.groups is defined else '' }}"
    password: "{{ item.password|default(omit) }}"
  with_items: "{{ baseline_users }}"
  tags:
    - baseline
    - users

- name: "Users | Set up SSH key for user {{ baseline_ssh_user|default('(not specified)') }}"
  authorized_key:
    user: "{{ baseline_ssh_user }}"
    key: "{{ baseline_ssh_key }}"
  when: baseline_ssh_user is defined
  tags:
    - baseline
    - users
